-- Stockcheck shared database. Run once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  category text not null,
  brand text not null,
  flavor text not null,
  name text not null,
  spec text not null default '',
  unit text not null default '件',
  pack_size integer not null default 1 check (pack_size > 0),
  low_stock_level integer not null default 0 check (low_stock_level >= 0),
  sort_order bigint generated by default as identity,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.stocktakes (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity >= 0),
  entered_quantity integer not null check (entered_quantity >= 0),
  entered_unit text not null,
  stocktake_date date not null default (now() at time zone 'Asia/Hong_Kong')::date,
  counted_by uuid default auth.uid() references auth.users(id),
  counted_by_email text not null default coalesce(auth.jwt()->>'email', 'team member'),
  created_at timestamptz not null default now()
);

create table if not exists public.stock_ins (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  pieces integer not null check (pieces > 0),
  units_added integer not null check (units_added > 0),
  entered_quantity integer not null check (entered_quantity > 0),
  entered_unit text not null,
  source text not null default '手動入貨',
  order_number text,
  added_by uuid default auth.uid() references auth.users(id),
  added_by_email text not null default coalesce(auth.jwt()->>'email', 'team member'),
  added_at timestamptz not null default now()
);

create index if not exists stocktakes_product_created_idx on public.stocktakes(product_id, created_at desc);
create index if not exists stock_ins_product_added_idx on public.stock_ins(product_id, added_at desc);
create unique index if not exists stock_ins_order_product_idx
  on public.stock_ins(order_number, product_id) where order_number is not null and order_number <> '';

alter table public.products enable row level security;
alter table public.stocktakes enable row level security;
alter table public.stock_ins enable row level security;

drop policy if exists "team reads products" on public.products;
create policy "team reads products" on public.products for select to authenticated using (true);
drop policy if exists "team adds products" on public.products;
create policy "team adds products" on public.products for insert to authenticated with check (created_by = auth.uid());
drop policy if exists "team updates products" on public.products;
create policy "team updates products" on public.products for update to authenticated using (true) with check (true);

drop policy if exists "team reads stocktakes" on public.stocktakes;
create policy "team reads stocktakes" on public.stocktakes for select to authenticated using (true);
drop policy if exists "team adds stocktakes" on public.stocktakes;
create policy "team adds stocktakes" on public.stocktakes for insert to authenticated with check (counted_by = auth.uid());

drop policy if exists "team reads stock ins" on public.stock_ins;
create policy "team reads stock ins" on public.stock_ins for select to authenticated using (true);
drop policy if exists "team adds stock ins" on public.stock_ins;
create policy "team adds stock ins" on public.stock_ins for insert to authenticated with check (added_by = auth.uid());

create or replace view public.inventory_current
with (security_invoker = true) as
select
  p.id, p.category, p.brand, p.flavor, p.name, p.spec, p.unit,
  p.pack_size, p.low_stock_level, p.sort_order,
  latest.quantity as latest_quantity,
  latest.stocktake_date,
  latest.counted_by_email,
  coalesce(sum(si.units_added) filter (
    where latest.created_at is null or si.added_at > latest.created_at
  ), 0)::integer as stock_in_after_count,
  coalesce(latest.quantity, 0)::integer + coalesce(sum(si.units_added) filter (
    where latest.created_at is null or si.added_at > latest.created_at
  ), 0)::integer as current_qty
from public.products p
left join lateral (
  select s.quantity, s.stocktake_date, s.counted_by_email, s.created_at
  from public.stocktakes s where s.product_id = p.id
  order by s.created_at desc limit 1
) latest on true
left join public.stock_ins si on si.product_id = p.id
group by p.id, latest.quantity, latest.stocktake_date, latest.counted_by_email, latest.created_at;

grant select on public.inventory_current to authenticated;

create or replace view public.recent_activity
with (security_invoker = true) as
select * from (
  select s.id, '盤點'::text as kind, p.name as product_name, s.quantity,
    s.counted_by_email as actor, s.created_at as happened_at
  from public.stocktakes s join public.products p on p.id = s.product_id
  union all
  select si.id, '入貨'::text as kind, p.name as product_name, si.units_added as quantity,
    si.added_by_email as actor, si.added_at as happened_at
  from public.stock_ins si join public.products p on p.id = si.product_id
) activity order by happened_at desc limit 30;

grant select on public.recent_activity to authenticated;
